package stockprediction.model;


import java.time.LocalDateTime;

/**
 * Represents a trading signal generated by the prediction engine
 */
public class PredictionSignal {
    public enum SignalType {
        LONG,    // Buy signal
        SHORT,   // Sell signal
        HOLD,    // No action
        REVERSAL // Potential reversal
    }

    private LocalDateTime timestamp;
    private SignalType signalType;
    private double confidence;
    private String reason;
    private double price;

    public PredictionSignal(LocalDateTime timestamp, SignalType signalType, double confidence, String reason, double price) {
        this.timestamp = timestamp;
        this.signalType = signalType;
        this.confidence = confidence;
        this.reason = reason;
        this.price = price;
    }

    // Getters and setters
    public LocalDateTime getTimestamp() { return timestamp; }
    public void setTimestamp(LocalDateTime timestamp) { this.timestamp = timestamp; }

    public SignalType getSignalType() { return signalType; }
    public void setSignalType(SignalType signalType) { this.signalType = signalType; }

    public double getConfidence() { return confidence; }
    public void setConfidence(double confidence) { this.confidence = confidence; }

    public String getReason() { return reason; }
    public void setReason(String reason) { this.reason = reason; }

    public double getPrice() { return price; }
    public void setPrice(double price) { this.price = price; }

    @Override
    public String toString() {
        return String.format("PredictionSignal{timestamp=%s, signal=%s, confidence=%.2f%%, reason='%s', price=%.2f}",
                timestamp, signalType, confidence * 100, reason, price);
    }
}
